name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.4'

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: latest

        # Optional: golangci-lint command line arguments.
        # args: --issues-exit-code=0
        args: --timeout=2m

        # Optional: show only new issues if it's a pull request. The default value is `false`.
        # only-new-issues: true

    - name: Install Protoc
      uses: arduino/setup-protoc@v1
      with:
        version: '3.12.4'

    - name: Unit tests
      run: go test -v -coverprofile=cover.out ./...

    - name: Send coverage
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: cover.out

    - name: Modver
      if: ${{ github.event_name == 'pull_request' }}
      uses: bobg/modver@v2.10.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pull_request_url: https://github.com/${{ github.repository }}/pull/${{ github.event.number }}
